In [1]:
import sys
!{sys.executable} -m pip install ucimlrepo scikit-learn pandas numpy scipy

from ucimlrepo import fetch_ucirepo
import pandas as pd
import numpy as np

statlog_german_credit_data = fetch_ucirepo(id=144)
X_raw = statlog_german_credit_data.data.features
y_raw = statlog_german_credit_data.data.targets

print(X_raw.shape, y_raw.shape)
X_raw.head()

Collecting ucimlrepo
  Using cached ucimlrepo-0.0.7-py3-none-any.whl.metadata (5.5 kB)
Collecting scikit-learn
  Using cached scikit_learn-1.9.0-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (11 kB)
Collecting pandas
  Using cached pandas-3.0.3-cp314-cp314-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting numpy
  Using cached numpy-2.5.0-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Collecting scipy
  Using cached scipy-1.18.0-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
Requirement already satisfied: certifi>=2020.12.5 in /home/OmkarArch/Documents/Projects/FinVeil/myenv/lib/python3.14/site-packages (from ucimlrepo) (2026.6.17)
Collecting joblib>=1.4.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Using cached narwhals-2.23.0-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/OmkarArch/Documents/Projects/FinVeil/myenv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/OmkarArch/Documents/Projects/FinVeil/myenv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached ucimlrepo-0.0.7-py3-none-any.whl (8.0 kB)
Using cached scikit_learn-1.9.0-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (9.1 MB)
Using cached pandas-3.0.3-cp314-cp314-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
Using cached numpy-2.5.0-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.7 MB)
Using cached scipy-1.18.0-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (35.3 MB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached narwhals-2.23.0-py3-none-any.whl (458 kB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, numpy, narwhals, joblib, scipy, pandas, ucimlrepo, scikit-learn
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8/8 [scikit-learn]0m 7/8 [scikit-learn]
Successfully installed joblib-1.5.3 narwhals-2.23.0 numpy-2.5.0 pandas-3.0.3 scikit-learn-1.9.0 scipy-1.18.0 threadpoolctl-3.6.0 ucimlrepo-0.0.7

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
(1000, 20) (1000, 1)

,Attribute1,Attribute2,Attribute3,Attribute4,Attribute5,Attribute6,Attribute7,Attribute8,Attribute9,Attribute10,Attribute11,Attribute12,Attribute13,Attribute14,Attribute15,Attribute16,Attribute17,Attribute18,Attribute19,Attribute20
0,A11,6,A34,A43,1169,A65,A75,4,A93,A101,4,A121,67,A143,A152,2,A173,1,A192,A201
1,A12,48,A32,A43,5951,A61,A73,2,A92,A101,2,A121,22,A143,A152,1,A173,1,A191,A201
2,A14,12,A34,A46,2096,A61,A74,2,A93,A101,3,A121,49,A143,A152,1,A172,2,A191,A201
3,A11,42,A32,A42,7882,A61,A74,2,A93,A103,4,A122,45,A143,A153,1,A173,2,A191,A201
4,A11,24,A33,A40,4870,A61,A73,3,A93,A101,4,A124,53,A143,A153,2,A173,2,A191,A201

In [2]:
import sys
!{sys.executable} -m pip install ucimlrepo scikit-learn pandas numpy scipy

from ucimlrepo import fetch_ucirepo
import pandas as pd
import numpy as np

statlog_german_credit_data = fetch_ucirepo(id=144)
X_raw = statlog_german_credit_data.data.features
y_raw = statlog_german_credit_data.data.targets

print(X_raw.shape, y_raw.shape)
X_raw.head()

Requirement already satisfied: ucimlrepo in /home/OmkarArch/Documents/Projects/FinVeil/myenv/lib/python3.14/site-packages (0.0.7)
Requirement already satisfied: scikit-learn in /home/OmkarArch/Documents/Projects/FinVeil/myenv/lib/python3.14/site-packages (1.9.0)
Requirement already satisfied: pandas in /home/OmkarArch/Documents/Projects/FinVeil/myenv/lib/python3.14/site-packages (3.0.3)
Requirement already satisfied: numpy in /home/OmkarArch/Documents/Projects/FinVeil/myenv/lib/python3.14/site-packages (2.5.0)
Requirement already satisfied: scipy in /home/OmkarArch/Documents/Projects/FinVeil/myenv/lib/python3.14/site-packages (1.18.0)
Requirement already satisfied: certifi>=2020.12.5 in /home/OmkarArch/Documents/Projects/FinVeil/myenv/lib/python3.14/site-packages (from ucimlrepo) (2026.6.17)
Requirement already satisfied: joblib>=1.4.0 in /home/OmkarArch/Documents/Projects/FinVeil/myenv/lib/python3.14/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in /home/OmkarArch/Documents/Projects/FinVeil/myenv/lib/python3.14/site-packages (from scikit-learn) (2.23.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in /home/OmkarArch/Documents/Projects/FinVeil/myenv/lib/python3.14/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/OmkarArch/Documents/Projects/FinVeil/myenv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/OmkarArch/Documents/Projects/FinVeil/myenv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
(1000, 20) (1000, 1)

,Attribute1,Attribute2,Attribute3,Attribute4,Attribute5,Attribute6,Attribute7,Attribute8,Attribute9,Attribute10,Attribute11,Attribute12,Attribute13,Attribute14,Attribute15,Attribute16,Attribute17,Attribute18,Attribute19,Attribute20
0,A11,6,A34,A43,1169,A65,A75,4,A93,A101,4,A121,67,A143,A152,2,A173,1,A192,A201
1,A12,48,A32,A43,5951,A61,A73,2,A92,A101,2,A121,22,A143,A152,1,A173,1,A191,A201
2,A14,12,A34,A46,2096,A61,A74,2,A93,A101,3,A121,49,A143,A152,1,A172,2,A191,A201
3,A11,42,A32,A42,7882,A61,A74,2,A93,A103,4,A122,45,A143,A153,1,A173,2,A191,A201
4,A11,24,A33,A40,4870,A61,A73,3,A93,A101,4,A124,53,A143,A153,2,A173,2,A191,A201

In [3]:
y = (y_raw.iloc[:, 0] == 1).astype(int)

categorical_cols = X_raw.select_dtypes(include="object").columns.tolist()
numeric_cols = X_raw.select_dtypes(exclude="object").columns.tolist()
print("Categorical:", categorical_cols)
print("Numeric:", numeric_cols)

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split

preprocessor = ColumnTransformer([
    ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols),
], remainder="passthrough")

X_encoded = preprocessor.fit_transform(X_raw)
encoded_feature_names = preprocessor.get_feature_names_out()

X_train_full, X_test_full, y_train, y_test = train_test_split(
    X_encoded, y, test_size=0.2, random_state=42, stratify=y
)
print("Full encoded train shape:", X_train_full.shape)

/tmp/ipykernel_11804/3163947569.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = X_raw.select_dtypes(include="object").columns.tolist()

Categorical: ['Attribute1', 'Attribute3', 'Attribute4', 'Attribute6', 'Attribute7', 'Attribute9', 'Attribute10', 'Attribute12', 'Attribute14', 'Attribute15', 'Attribute17', 'Attribute19', 'Attribute20']
Numeric: ['Attribute2', 'Attribute5', 'Attribute8', 'Attribute11', 'Attribute13', 'Attribute16', 'Attribute18']
Full encoded train shape: (800, 61)

In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

baseline_model = LogisticRegression(max_iter=2000)
baseline_model.fit(X_train_full, y_train)

baseline_preds = baseline_model.predict(X_test_full)
baseline_accuracy = accuracy_score(y_test, baseline_preds)
print(f"Baseline (full features, true sigmoid) accuracy: {baseline_accuracy:.4f}")

Baseline (full features, true sigmoid) accuracy: 0.7150

/home/OmkarArch/Documents/Projects/FinVeil/myenv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 2000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=2000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [5]:
N_FEATURES = 6  # tune between 5-8

coef_series = pd.Series(baseline_model.coef_[0], index=encoded_feature_names)
top_features = coef_series.abs().sort_values(ascending=False).head(N_FEATURES).index.tolist()

print("Selected features for Profile struct:")
for f in top_features:
    print(f"  {f}: coef={coef_series[f]:+.4f}")

feature_idx = [list(encoded_feature_names).index(f) for f in top_features]

X_train_small = np.asarray(X_train_full[:, feature_idx].todense()
                            if hasattr(X_train_full, "todense") else X_train_full[:, feature_idx])
X_test_small = np.asarray(X_test_full[:, feature_idx].todense()
                           if hasattr(X_test_full, "todense") else X_test_full[:, feature_idx])

Selected features for Profile struct:
  cat__Attribute4_A41: coef=+1.3581
  cat__Attribute10_A103: coef=+1.0464
  cat__Attribute1_A14: coef=+1.0403
  cat__Attribute3_A34: coef=+0.8697
  cat__Attribute20_A202: coef=+0.8300
  cat__Attribute6_A64: coef=+0.7120

In [6]:
small_model = LogisticRegression(max_iter=2000)
small_model.fit(X_train_small, y_train)

small_preds = small_model.predict(X_test_small)
small_accuracy = accuracy_score(y_test, small_preds)
print(f"Small model ({N_FEATURES} features, true sigmoid) accuracy: {small_accuracy:.4f}")
print(f"Accuracy lost by reducing to {N_FEATURES} features: {baseline_accuracy - small_accuracy:+.4f}")

weights = small_model.coef_[0]
bias = small_model.intercept_[0]
print("Weights:", weights)
print("Bias:", bias)

Small model (6 features, true sigmoid) accuracy: 0.6600
Accuracy lost by reducing to 6 features: +0.0550
Weights: [1.09615329 1.20861459 1.56469577 0.74482977 1.04779668 0.85221622]
Bias: -0.0463340354105687

In [7]:
from scipy.optimize import curve_fit

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def poly2(z, c0, c1, c2):
    return c0 + c1 * z + c2 * z ** 2

z_train = small_model.decision_function(X_train_small)
z_test = small_model.decision_function(X_test_small)

margin = 0.1 * (z_train.max() - z_train.min())
z_range = np.linspace(z_train.min() - margin, z_train.max() + margin, 400)

coeffs, _ = curve_fit(poly2, z_range, sigmoid(z_range))
c0, c1, c2 = coeffs
print(f"Fitted polynomial coefficients: c0={c0:.6f}, c1={c1:.6f}, c2={c2:.6f}")

poly_probs_test = poly2(z_test, c0, c1, c2)
poly_preds_test = (poly_probs_test >= 0.5).astype(int)
poly_accuracy = accuracy_score(y_test, poly_preds_test)

true_probs_test = sigmoid(z_test)
mean_abs_prob_error = np.abs(poly_probs_test - true_probs_test).mean()

print(f"Small model, true sigmoid accuracy:      {small_accuracy:.4f}")
print(f"Small model, polynomial-activation acc:  {poly_accuracy:.4f}")
print(f"Accuracy delta (poly - sigmoid):          {poly_accuracy - small_accuracy:+.4f}")
print(f"Mean absolute probability error:          {mean_abs_prob_error:.4f}")

Fitted polynomial coefficients: c0=0.508981, c1=0.242376, c2=-0.030375
Small model, true sigmoid accuracy:      0.6600
Small model, polynomial-activation acc:  0.6600
Accuracy delta (poly - sigmoid):          +0.0000
Mean absolute probability error:          0.0093

In [8]:
SCALE = 1000      # fixed-point scale for weights/coeffs
OFFSET = 100_000  # large enough that (value * SCALE) + OFFSET is always >= 0

def quantize_signed(value, scale=SCALE):
    return int(round(value * scale))

def to_unsigned(signed_int, offset=OFFSET):
    v = signed_int + offset
    assert v >= 0, f"OFFSET too small for value {signed_int}; increase OFFSET"
    return v

quantized_weights_signed = [quantize_signed(w) for w in weights]
quantized_bias_signed = quantize_signed(bias)

quantized_weights_unsigned = [to_unsigned(w) for w in quantized_weights_signed]
quantized_bias_unsigned = to_unsigned(quantized_bias_signed)

quantized_c0_signed = quantize_signed(c0)
quantized_c1_signed = quantize_signed(c1)
quantized_c2_signed = quantize_signed(c2)

quantized_c0_unsigned = to_unsigned(quantized_c0_signed)
quantized_c1_unsigned = to_unsigned(quantized_c1_signed)
quantized_c2_unsigned = to_unsigned(quantized_c2_signed)

print("Quantized (unsigned, CoFHE-ready) weights:", quantized_weights_unsigned)
print("Quantized (unsigned) bias:", quantized_bias_unsigned)
print("Quantized (unsigned) poly coeffs [c0, c1, c2]:",
      [quantized_c0_unsigned, quantized_c1_unsigned, quantized_c2_unsigned])

Quantized (unsigned, CoFHE-ready) weights: [101096, 101209, 101565, 100745, 101048, 100852]
Quantized (unsigned) bias: 99954
Quantized (unsigned) poly coeffs [c0, c1, c2]: [100509, 100242, 99970]

In [9]:
N = len(top_features)
FEATURE_SCALE = 100  # separate scale for feature values, tune to their real range

def full_simulation(feature_values):
    z_unsigned_terms = []
    offset_removal = 0
    for qw_unsigned, fv in zip(quantized_weights_unsigned, feature_values):
        fv_q = int(round(fv * FEATURE_SCALE))
        z_unsigned_terms.append(qw_unsigned * fv_q)
        offset_removal += OFFSET * fv_q
    z_unsigned_terms.append(quantized_bias_unsigned)
    offset_removal += OFFSET

    z_unsigned_sum = sum(z_unsigned_terms)
    z_signed_scaled = z_unsigned_sum - offset_removal   # == z * SCALE * FEATURE_SCALE
    z_reconstructed = z_signed_scaled / (SCALE * FEATURE_SCALE)
    return z_reconstructed

sample_idx = 0
z_true = z_test[sample_idx]
z_sim = full_simulation(X_test_small[sample_idx])
print(f"True z (float):        {z_true:.6f}")
print(f"Simulated z (CoFHE):   {z_sim:.6f}")
print(f"Difference:            {abs(z_true - z_sim):.6f}")

True z (float):        -0.046334
Simulated z (CoFHE):   -0.000460
Difference:            0.045874

In [10]:
z_sim_all = np.array([full_simulation(row) for row in X_test_small])

def poly2_quantized_reconstructed(z):
    c0_r = (quantized_c0_unsigned - OFFSET) / SCALE
    c1_r = (quantized_c1_unsigned - OFFSET) / SCALE
    c2_r = (quantized_c2_unsigned - OFFSET) / SCALE
    return c0_r + c1_r * z + c2_r * z ** 2

sim_probs = poly2_quantized_reconstructed(z_sim_all)
sim_preds = (sim_probs >= 0.5).astype(int)
sim_accuracy = accuracy_score(y_test, sim_preds)

print(f"True sigmoid accuracy:                {small_accuracy:.4f}")
print(f"Float polynomial-activation accuracy: {poly_accuracy:.4f}")
print(f"Quantized/offset CoFHE-sim accuracy:  {sim_accuracy:.4f}")
print(f"Quantization error vs float poly:     {sim_accuracy - poly_accuracy:+.4f}")

True sigmoid accuracy:                0.6600
Float polynomial-activation accuracy: 0.6600
Quantized/offset CoFHE-sim accuracy:  0.7000
Quantization error vs float poly:     +0.0400

In [11]:
EUINT32_MAX = 2**32 - 1

max_weight_term = max(quantized_weights_unsigned) * (FEATURE_SCALE * max(np.abs(X_test_small).max(), 1))
print(f"Largest individual multiply term (approx): {max_weight_term:,.0f}")
print(f"euint32 max:                                {EUINT32_MAX:,}")
print(f"Headroom OK: {max_weight_term < EUINT32_MAX}")

if max_weight_term >= EUINT32_MAX:
    print("WARNING: reduce OFFSET/SCALE/FEATURE_SCALE, or move to a wider encrypted type.")

Largest individual multiply term (approx): 10,156,500
euint32 max:                                4,294,967,295
Headroom OK: True

In [12]:
print("=" * 60)
print("CONTRACT-READY CONSTANTS")
print("=" * 60)
print(f"Selected features (order matters, matches Profile struct): {top_features}")
print(f"SCALE = {SCALE}")
print(f"FEATURE_SCALE = {FEATURE_SCALE}")
print(f"OFFSET = {OFFSET}")
print(f"Quantized unsigned weights: {quantized_weights_unsigned}")
print(f"Quantized unsigned bias: {quantized_bias_unsigned}")
print(f"Quantized unsigned poly coeffs [c0, c1, c2]: "
      f"[{quantized_c0_unsigned}, {quantized_c1_unsigned}, {quantized_c2_unsigned}]")
print("=" * 60)
print(f"Accuracy summary — true sigmoid: {small_accuracy:.4f} | "
      f"float polynomial: {poly_accuracy:.4f} | "
      f"quantized CoFHE-sim: {sim_accuracy:.4f}")

============================================================
CONTRACT-READY CONSTANTS
============================================================
Selected features (order matters, matches Profile struct): ['cat__Attribute4_A41', 'cat__Attribute10_A103', 'cat__Attribute1_A14', 'cat__Attribute3_A34', 'cat__Attribute20_A202', 'cat__Attribute6_A64']
SCALE = 1000
FEATURE_SCALE = 100
OFFSET = 100000
Quantized unsigned weights: [101096, 101209, 101565, 100745, 101048, 100852]
Quantized unsigned bias: 99954
Quantized unsigned poly coeffs [c0, c1, c2]: [100509, 100242, 99970]
============================================================
Accuracy summary — true sigmoid: 0.6600 | float polynomial: 0.6600 | quantized CoFHE-sim: 0.7000

In [13]:
# Force in known strong numeric predictors, then fill remaining slots by ranked importance
forced_features = ["remainder__Attribute2", "remainder__Attribute5", "remainder__Attribute13"]
# (these correspond to Duration, CreditAmount, Age — verify exact names via encoded_feature_names)

remaining_slots = N_FEATURES - len(forced_features)
ranked_rest = coef_series.drop(index=forced_features, errors="ignore") \
                          .abs().sort_values(ascending=False).head(remaining_slots).index.tolist()

top_features = forced_features + ranked_rest
print(top_features)

['remainder__Attribute2', 'remainder__Attribute5', 'remainder__Attribute13', 'cat__Attribute4_A41', 'cat__Attribute10_A103', 'cat__Attribute1_A14']

In [14]:
feature_idx = [list(encoded_feature_names).index(f) for f in top_features]

X_train_small = np.asarray(X_train_full[:, feature_idx].todense()
                            if hasattr(X_train_full, "todense") else X_train_full[:, feature_idx])
X_test_small = np.asarray(X_test_full[:, feature_idx].todense()
                           if hasattr(X_test_full, "todense") else X_test_full[:, feature_idx])

small_model = LogisticRegression(max_iter=2000)
small_model.fit(X_train_small, y_train)

small_preds = small_model.predict(X_test_small)
small_accuracy = accuracy_score(y_test, small_preds)
print(f"Small model ({N_FEATURES} features, true sigmoid) accuracy: {small_accuracy:.4f}")

weights = small_model.coef_[0]
bias = small_model.intercept_[0]
print("Weights:", weights)
print("Bias:", bias)

Small model (6 features, true sigmoid) accuracy: 0.6800
Weights: [-3.41819158e-02 -4.64787052e-05  1.94731711e-02  1.40375989e+00
  1.14567027e+00  1.65359162e+00]
Bias: 0.37056176446332173

In [15]:
from sklearn.preprocessing import StandardScaler

small_scaler = StandardScaler(with_mean=True)
X_train_small_scaled = small_scaler.fit_transform(X_train_small)
X_test_small_scaled = small_scaler.transform(X_test_small)

small_model = LogisticRegression(max_iter=2000)
small_model.fit(X_train_small_scaled, y_train)

small_preds = small_model.predict(X_test_small_scaled)
small_accuracy = accuracy_score(y_test, small_preds)
print(f"Small model ({N_FEATURES} features, true sigmoid) accuracy: {small_accuracy:.4f}")

# Convert scaled weights back to raw-feature-unit weights, since the contract
# takes raw applicant inputs (Duration in months, CreditAmount in currency), not z-scores
w_scaled = small_model.coef_[0]
b_scaled = small_model.intercept_[0]

weights = w_scaled / small_scaler.scale_
bias = b_scaled - np.sum(w_scaled * small_scaler.mean_ / small_scaler.scale_)

print("Weights (raw-unit, contract-ready):", weights)
print("Bias (raw-unit, contract-ready):", bias)

# sanity check: this should match small_accuracy above
z_check = X_test_small @ weights + bias
check_preds = (z_check >= 0).astype(int)
print("Sanity check accuracy (raw weights):", accuracy_score(y_test, check_preds))

Small model (6 features, true sigmoid) accuracy: 0.6650
Weights (raw-unit, contract-ready): [-3.43452060e-02 -5.00054863e-05  1.90940642e-02  1.59685033e+00
  1.38535734e+00  1.71606231e+00]
Bias (raw-unit, contract-ready): 0.36426796603676115
Sanity check accuracy (raw weights): 0.665

In [16]:
attribute1_cols = [f for f in encoded_feature_names if f.startswith("cat__Attribute1_")]
attribute3_cols = [f for f in encoded_feature_names if f.startswith("cat__Attribute3_")]
print(attribute1_cols, attribute3_cols)

['cat__Attribute1_A11', 'cat__Attribute1_A12', 'cat__Attribute1_A13', 'cat__Attribute1_A14'] ['cat__Attribute3_A30', 'cat__Attribute3_A31', 'cat__Attribute3_A32', 'cat__Attribute3_A33', 'cat__Attribute3_A34']

In [17]:
core_numeric = ["remainder__Attribute2", "remainder__Attribute5"]  # Duration, CreditAmount
core_categorical_groups = attribute1_cols + attribute3_cols  # ALL levels of checking status + credit history

top_features = core_numeric + core_categorical_groups
print(f"Total features: {len(top_features)}")
print(top_features)

feature_idx = [list(encoded_feature_names).index(f) for f in top_features]

X_train_small = np.asarray(X_train_full[:, feature_idx].todense()
                            if hasattr(X_train_full, "todense") else X_train_full[:, feature_idx])
X_test_small = np.asarray(X_test_full[:, feature_idx].todense()
                           if hasattr(X_test_full, "todense") else X_test_full[:, feature_idx])

small_model = LogisticRegression(max_iter=2000)
small_model.fit(X_train_small, y_train)

small_preds = small_model.predict(X_test_small)
small_accuracy = accuracy_score(y_test, small_preds)
print(f"Small model ({len(top_features)} features, true sigmoid) accuracy: {small_accuracy:.4f}")

weights = small_model.coef_[0]
bias = small_model.intercept_[0]

Total features: 11
['remainder__Attribute2', 'remainder__Attribute5', 'cat__Attribute1_A11', 'cat__Attribute1_A12', 'cat__Attribute1_A13', 'cat__Attribute1_A14', 'cat__Attribute3_A30', 'cat__Attribute3_A31', 'cat__Attribute3_A32', 'cat__Attribute3_A33', 'cat__Attribute3_A34']
Small model (11 features, true sigmoid) accuracy: 0.7600

In [18]:
for name, w in zip(top_features, weights):
    print(f"{name}: {w:+.4f}")
print(f"bias: {bias:+.4f}")

remainder__Attribute2: -0.0301
remainder__Attribute5: -0.0000
cat__Attribute1_A11: -0.8144
cat__Attribute1_A12: -0.3341
cat__Attribute1_A13: +0.1327
cat__Attribute1_A14: +1.0204
cat__Attribute3_A30: -0.5544
cat__Attribute3_A31: -0.4785
cat__Attribute3_A32: +0.1627
cat__Attribute3_A33: +0.0853
cat__Attribute3_A34: +0.7895
bias: +1.3115

In [19]:
from sklearn.preprocessing import StandardScaler

numeric_idx = [0, 1]  # positions of remainder__Attribute2, remainder__Attribute5 in top_features
categorical_idx = list(range(2, len(top_features)))

scaler = StandardScaler()
X_train_numeric_scaled = scaler.fit_transform(X_train_small[:, numeric_idx])
X_test_numeric_scaled = scaler.transform(X_test_small[:, numeric_idx])

X_train_small_mixed = np.hstack([X_train_numeric_scaled, X_train_small[:, categorical_idx]])
X_test_small_mixed = np.hstack([X_test_numeric_scaled, X_test_small[:, categorical_idx]])

small_model = LogisticRegression(max_iter=2000)
small_model.fit(X_train_small_mixed, y_train)

small_preds = small_model.predict(X_test_small_mixed)
small_accuracy = accuracy_score(y_test, small_preds)
print(f"Small model ({len(top_features)} features, true sigmoid) accuracy: {small_accuracy:.4f}")

w_scaled_numeric = small_model.coef_[0][:2]
w_categorical = small_model.coef_[0][2:]
b_scaled = small_model.intercept_[0]

# convert only the numeric weights back to raw units; categorical weights are already raw
weights_numeric_raw = w_scaled_numeric / scaler.scale_
bias = b_scaled - np.sum(w_scaled_numeric * scaler.mean_ / scaler.scale_)

weights = np.concatenate([weights_numeric_raw, w_categorical])

print("Weights (raw-unit, contract-ready):", dict(zip(top_features, weights)))
print("Bias:", bias)

# sanity check
z_check = X_test_small @ weights + bias
check_preds = (z_check >= 0).astype(int)
print("Sanity check accuracy:", accuracy_score(y_test, check_preds))

Small model (11 features, true sigmoid) accuracy: 0.7650
Weights (raw-unit, contract-ready): {'remainder__Attribute2': np.float64(-0.029860640680443567), 'remainder__Attribute5': np.float64(-1.2380294605124616e-05), 'cat__Attribute1_A11': np.float64(-0.8126846637384812), 'cat__Attribute1_A12': np.float64(-0.3315956124455708), 'cat__Attribute1_A13': np.float64(0.1267255116982299), 'cat__Attribute1_A14': np.float64(1.0236168460640787), 'cat__Attribute3_A30': np.float64(-0.5558736946961778), 'cat__Attribute3_A31': np.float64(-0.4761613708150015), 'cat__Attribute3_A32': np.float64(0.16416610936943496), 'cat__Attribute3_A33': np.float64(0.08368120799725151), 'cat__Attribute3_A34': np.float64(0.7902498297227554)}
Bias: 1.3055925485141842
Sanity check accuracy: 0.765

In [20]:
z_train = X_train_small @ weights + bias
z_test = X_test_small @ weights + bias

print("z_train range:", z_train.min(), "to", z_train.max())
print("z_test range:", z_test.min(), "to", z_test.max())

z_train range: -1.5844118798756481 to 2.9820033329287874
z_test range: -1.4768083904259544 to 2.9013971244761723

In [21]:
from sklearn.linear_model import LogisticRegression

print(f"{'C':>6} | {'nonzero features':>17} | {'accuracy':>8}")
for C_val in [1.0, 0.5, 0.3, 0.2, 0.15, 0.1, 0.07, 0.05]:
    l1_model = LogisticRegression(penalty='l1', solver='liblinear', C=C_val, max_iter=2000)
    l1_model.fit(X_train_small_mixed, y_train)
    acc = accuracy_score(y_test, l1_model.predict(X_test_small_mixed))
    nonzero = np.sum(np.abs(l1_model.coef_[0]) > 1e-6)
    print(f"{C_val:>6.2f} | {nonzero:>17} | {acc:>8.4f}")

     C |  nonzero features | accuracy
  1.00 |                10 |   0.7600
  0.50 |                10 |   0.7600
  0.30 |                 8 |   0.7550
  0.20 |                 7 |   0.7400
  0.15 |                 6 |   0.7350
  0.10 |                 5 |   0.7150
  0.07 |                 4 |   0.7150
  0.05 |                 3 |   0.7150

/home/OmkarArch/Documents/Projects/FinVeil/myenv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/OmkarArch/Documents/Projects/FinVeil/myenv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/home/OmkarArch/Documents/Projects/FinVeil/myenv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/OmkarArch/Documents/Projects/FinVeil/myenv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/home/OmkarArch/Documents/Projects/FinVeil/myenv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/OmkarArch/Documents/Projects/FinVeil/myenv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/home/OmkarArch/Documents/Projects/FinVeil/myenv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/OmkarArch/Documents/Projects/FinVeil/myenv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/home/OmkarArch/Documents/Projects/FinVeil/myenv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/OmkarArch/Documents/Projects/FinVeil/myenv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/home/OmkarArch/Documents/Projects/FinVeil/myenv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/OmkarArch/Documents/Projects/FinVeil/myenv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/home/OmkarArch/Documents/Projects/FinVeil/myenv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/OmkarArch/Documents/Projects/FinVeil/myenv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/home/OmkarArch/Documents/Projects/FinVeil/myenv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/OmkarArch/Documents/Projects/FinVeil/myenv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

In [22]:
CHOSEN_C = 0.2  # replace with whatever the table shows as the sweet spot

l1_model = LogisticRegression(penalty='l1', solver='liblinear', C=CHOSEN_C, max_iter=2000)
l1_model.fit(X_train_small_mixed, y_train)

surviving_mask = np.abs(l1_model.coef_[0]) > 1e-6
surviving_features = [f for f, keep in zip(top_features, surviving_mask) if keep]
dropped_features = [f for f, keep in zip(top_features, surviving_mask) if not keep]

print("Surviving features:", surviving_features)
print("Dropped (zero-weight) features:", dropped_features)

Surviving features: ['remainder__Attribute2', 'remainder__Attribute5', 'cat__Attribute1_A11', 'cat__Attribute1_A13', 'cat__Attribute1_A14', 'cat__Attribute3_A32', 'cat__Attribute3_A34']
Dropped (zero-weight) features: ['cat__Attribute1_A12', 'cat__Attribute3_A30', 'cat__Attribute3_A31', 'cat__Attribute3_A33']

/home/OmkarArch/Documents/Projects/FinVeil/myenv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/OmkarArch/Documents/Projects/FinVeil/myenv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

In [23]:
print(l1_model.coef_[0])
print("Exact zeros:", np.sum(l1_model.coef_[0] == 0.0))
print("Near-zero but nonzero:", np.sum((np.abs(l1_model.coef_[0]) > 0) & (np.abs(l1_model.coef_[0]) < 1e-6)))

[-0.35449347 -0.02596659 -0.38136052  0.          0.00853115  1.2900275
  0.          0.          0.18894383  0.          0.75640645]
Exact zeros: 4
Near-zero but nonzero: 0

In [24]:
l1_model = LogisticRegression(solver='saga', l1_ratio=1.0, penalty='elasticnet', C=0.3, max_iter=5000)

In [25]:
final_features = surviving_features  # the 7 features from your last run
print("Final feature set:", final_features)
print("Field count for contract:", len(final_features))

final_idx = [list(encoded_feature_names).index(f) for f in final_features]

X_train_final = np.asarray(X_train_full[:, final_idx].todense()
                            if hasattr(X_train_full, "todense") else X_train_full[:, final_idx])
X_test_final = np.asarray(X_test_full[:, final_idx].todense()
                           if hasattr(X_test_full, "todense") else X_test_full[:, final_idx])

# identify which of the final columns are numeric (need scaling) vs one-hot (don't)
numeric_final_idx = [i for i, f in enumerate(final_features) if f.startswith("remainder__")]
categorical_final_idx = [i for i, f in enumerate(final_features) if f.startswith("cat__")]

scaler = StandardScaler()
X_train_num_scaled = scaler.fit_transform(X_train_final[:, numeric_final_idx])
X_test_num_scaled = scaler.transform(X_test_final[:, numeric_final_idx])

X_train_final_mixed = np.hstack([X_train_num_scaled, X_train_final[:, categorical_final_idx]])
X_test_final_mixed = np.hstack([X_test_num_scaled, X_test_final[:, categorical_final_idx]])

final_model = LogisticRegression(max_iter=2000)
final_model.fit(X_train_final_mixed, y_train)

final_accuracy = accuracy_score(y_test, final_model.predict(X_test_final_mixed))
print(f"Final pruned model ({len(final_features)} features) accuracy: {final_accuracy:.4f}")

# convert scaled numeric weights back to raw units; categorical weights stay as-is
w_scaled_numeric = final_model.coef_[0][:len(numeric_final_idx)]
w_categorical = final_model.coef_[0][len(numeric_final_idx):]
b_scaled = final_model.intercept_[0]

weights_numeric_raw = w_scaled_numeric / scaler.scale_
bias = b_scaled - np.sum(w_scaled_numeric * scaler.mean_ / scaler.scale_)

# reorder weights back to match final_features order (numeric first, then categorical --
# matches how we built X_train_final_mixed above)
weights = np.concatenate([weights_numeric_raw, w_categorical])

print("Weights (raw-unit, contract-ready):")
for name, w in zip(final_features, weights):
    print(f"  {name}: {w:+.4f}")
print(f"Bias: {bias:+.4f}")

# sanity check: raw weights against raw (unscaled) features should reproduce final_accuracy
z_check = X_test_final @ weights + bias
check_preds = (z_check >= 0).astype(int)
print("Sanity check accuracy:", accuracy_score(y_test, check_preds))

Final feature set: ['remainder__Attribute2', 'remainder__Attribute5', 'cat__Attribute1_A11', 'cat__Attribute1_A13', 'cat__Attribute1_A14', 'cat__Attribute3_A32', 'cat__Attribute3_A34']
Field count for contract: 7
Final pruned model (7 features) accuracy: 0.7500
Weights (raw-unit, contract-ready):
  remainder__Attribute2: -0.0299
  remainder__Attribute5: -0.0000
  cat__Attribute1_A11: -0.5246
  cat__Attribute1_A13: +0.3966
  cat__Attribute1_A14: +1.3435
  cat__Attribute3_A32: +0.3858
  cat__Attribute3_A34: +1.0085
Bias: +0.7778
Sanity check accuracy: 0.75

In [26]:
final_features_6 = ['remainder__Attribute2', 'cat__Attribute1_A11', 'cat__Attribute1_A13',
                     'cat__Attribute1_A14', 'cat__Attribute3_A32', 'cat__Attribute3_A34']

final_idx_6 = [list(encoded_feature_names).index(f) for f in final_features_6]
X_train_final_6 = np.asarray(X_train_full[:, final_idx_6].todense()
                              if hasattr(X_train_full, "todense") else X_train_full[:, final_idx_6])
X_test_final_6 = np.asarray(X_test_full[:, final_idx_6].todense()
                             if hasattr(X_test_full, "todense") else X_test_full[:, final_idx_6])

numeric_idx_6 = [0]  # just Attribute2 (Duration)
categorical_idx_6 = list(range(1, 6))

scaler6 = StandardScaler()
X_train_num6 = scaler6.fit_transform(X_train_final_6[:, numeric_idx_6])
X_test_num6 = scaler6.transform(X_test_final_6[:, numeric_idx_6])

X_train_6_mixed = np.hstack([X_train_num6, X_train_final_6[:, categorical_idx_6]])
X_test_6_mixed = np.hstack([X_test_num6, X_test_final_6[:, categorical_idx_6]])

model_6 = LogisticRegression(max_iter=2000)
model_6.fit(X_train_6_mixed, y_train)
acc_6 = accuracy_score(y_test, model_6.predict(X_test_6_mixed))
print(f"6-feature model accuracy: {acc_6:.4f}  (vs 7-feature: 0.7500)")

6-feature model accuracy: 0.7450  (vs 7-feature: 0.7500)

In [27]:
w_scaled_numeric_6 = model_6.coef_[0][:1]        # just Attribute2 (Duration)
w_categorical_6 = model_6.coef_[0][1:]           # the 5 one-hot levels
b_scaled_6 = model_6.intercept_[0]

weights_numeric_raw_6 = w_scaled_numeric_6 / scaler6.scale_
bias = b_scaled_6 - np.sum(w_scaled_numeric_6 * scaler6.mean_ / scaler6.scale_)

weights = np.concatenate([weights_numeric_raw_6, w_categorical_6])
top_features = final_features_6
N_FEATURES = len(top_features)

print("Final weights (raw-unit, contract-ready):")
for name, w in zip(top_features, weights):
    print(f"  {name}: {w:+.4f}")
print(f"Bias: {bias:+.4f}")

# sanity check
z_check_final = X_test_final_6 @ weights + bias
check_preds_final = (z_check_final >= 0).astype(int)
print("Sanity check accuracy:", accuracy_score(y_test, check_preds_final))

small_model = model_6
small_accuracy = acc_6
X_train_small = X_train_final_6
X_test_small = X_test_final_6

Final weights (raw-unit, contract-ready):
  remainder__Attribute2: -0.0318
  cat__Attribute1_A11: -0.5213
  cat__Attribute1_A13: +0.4141
  cat__Attribute1_A14: +1.3462
  cat__Attribute3_A32: +0.3880
  cat__Attribute3_A34: +1.0096
Bias: +0.7694
Sanity check accuracy: 0.745

In [28]:
from scipy.optimize import curve_fit

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def poly2(z, c0, c1, c2):
    return c0 + c1 * z + c2 * z ** 2

z_train = X_train_small @ weights + bias
z_test = X_test_small @ weights + bias

margin = 0.1 * (z_train.max() - z_train.min())
z_range = np.linspace(z_train.min() - margin, z_train.max() + margin, 400)

coeffs, _ = curve_fit(poly2, z_range, sigmoid(z_range))
c0, c1, c2 = coeffs
print(f"Fitted polynomial coefficients: c0={c0:.6f}, c1={c1:.6f}, c2={c2:.6f}")

poly_probs_test = poly2(z_test, c0, c1, c2)
poly_preds_test = (poly_probs_test >= 0.5).astype(int)
poly_accuracy = accuracy_score(y_test, poly_preds_test)

true_probs_test = sigmoid(z_test)
mean_abs_prob_error = np.abs(poly_probs_test - true_probs_test).mean()

print(f"True sigmoid accuracy:          {small_accuracy:.4f}")
print(f"Float polynomial-activation acc: {poly_accuracy:.4f}")
print(f"Mean absolute probability error: {mean_abs_prob_error:.4f}")

Fitted polynomial coefficients: c0=0.522897, c1=0.200176, c2=-0.016962
True sigmoid accuracy:          0.7450
Float polynomial-activation acc: 0.7450
Mean absolute probability error: 0.0230

In [29]:
SCALE = 1000
OFFSET = 100_000

def quantize_signed(value, scale=SCALE):
    return int(round(value * scale))

def to_unsigned(signed_int, offset=OFFSET):
    v = signed_int + offset
    assert v >= 0, f"OFFSET too small for value {signed_int}; increase OFFSET"
    return v

quantized_weights_signed = [quantize_signed(w) for w in weights]
quantized_bias_signed = quantize_signed(bias)
quantized_weights_unsigned = [to_unsigned(w) for w in quantized_weights_signed]
quantized_bias_unsigned = to_unsigned(quantized_bias_signed)

quantized_c0_unsigned = to_unsigned(quantize_signed(c0))
quantized_c1_unsigned = to_unsigned(quantize_signed(c1))
quantized_c2_unsigned = to_unsigned(quantize_signed(c2))

print("Quantized unsigned weights:", quantized_weights_unsigned)
print("Quantized unsigned bias:", quantized_bias_unsigned)
print("Quantized unsigned poly coeffs:", [quantized_c0_unsigned, quantized_c1_unsigned, quantized_c2_unsigned])

Quantized unsigned weights: [99968, 99479, 100414, 101346, 100388, 101010]
Quantized unsigned bias: 100769
Quantized unsigned poly coeffs: [100523, 100200, 99983]

In [30]:
N = len(top_features)
FEATURE_SCALE = 100

def full_simulation(feature_values):
    z_unsigned_terms = []
    offset_removal = 0
    for qw_unsigned, fv in zip(quantized_weights_unsigned, feature_values):
        fv_q = int(round(fv * FEATURE_SCALE))
        z_unsigned_terms.append(qw_unsigned * fv_q)
        offset_removal += OFFSET * fv_q
    z_unsigned_terms.append(quantized_bias_unsigned)
    offset_removal += OFFSET

    z_unsigned_sum = sum(z_unsigned_terms)
    z_signed_scaled = z_unsigned_sum - offset_removal
    return z_signed_scaled / (SCALE * FEATURE_SCALE)

z_sim_all = np.array([full_simulation(row) for row in X_test_small])

def poly2_quantized_reconstructed(z):
    c0_r = (quantized_c0_unsigned - OFFSET) / SCALE
    c1_r = (quantized_c1_unsigned - OFFSET) / SCALE
    c2_r = (quantized_c2_unsigned - OFFSET) / SCALE
    return c0_r + c1_r * z + c2_r * z ** 2

sim_probs = poly2_quantized_reconstructed(z_sim_all)
sim_preds = (sim_probs >= 0.5).astype(int)
sim_accuracy = accuracy_score(y_test, sim_preds)

print(f"True sigmoid accuracy:                {small_accuracy:.4f}")
print(f"Float polynomial-activation accuracy: {poly_accuracy:.4f}")
print(f"Quantized/offset CoFHE-sim accuracy:  {sim_accuracy:.4f}")

True sigmoid accuracy:                0.7450
Float polynomial-activation accuracy: 0.7450
Quantized/offset CoFHE-sim accuracy:  0.7100

In [31]:
EUINT32_MAX = 2**32 - 1
max_weight_term = max(quantized_weights_unsigned) * (FEATURE_SCALE * max(np.abs(X_test_small).max(), 1))
print(f"Largest individual multiply term: {max_weight_term:,.0f}")
print(f"euint32 max: {EUINT32_MAX:,}")
print(f"Headroom OK: {max_weight_term < EUINT32_MAX}")

Largest individual multiply term: 608,076,000
euint32 max: 4,294,967,295
Headroom OK: True

In [32]:
print(f"c0={c0:.6f}, c1={c1:.6f}, c2={c2:.6f}")
print(f"Quantized (before offset): c0*SCALE={c0*SCALE:.2f}, c1*SCALE={c1*SCALE:.2f}, c2*SCALE={c2*SCALE:.2f}")

c0=0.522897, c1=0.200176, c2=-0.016962
Quantized (before offset): c0*SCALE=522.90, c1*SCALE=200.18, c2*SCALE=-16.96

In [33]:
POLY_SCALE = 1_000_000  # much finer resolution than weight SCALE, since c2 is tiny

def quantize_signed_poly(value, scale=POLY_SCALE):
    return int(round(value * scale))

quantized_c0_signed = quantize_signed_poly(c0)
quantized_c1_signed = quantize_signed_poly(c1)
quantized_c2_signed = quantize_signed_poly(c2)

quantized_c0_unsigned = to_unsigned(quantized_c0_signed)
quantized_c1_unsigned = to_unsigned(quantized_c1_signed)
quantized_c2_unsigned = to_unsigned(quantized_c2_signed)

print("Poly coeffs before rounding:", c0, c1, c2)
print("Quantized unsigned poly coeffs:", [quantized_c0_unsigned, quantized_c1_unsigned, quantized_c2_unsigned])

Poly coeffs before rounding: 0.5228971855175579 0.20017594866079758 -0.01696234669199987
Quantized unsigned poly coeffs: [622897, 300176, 83038]

In [34]:
def poly2_quantized_reconstructed(z):
    c0_r = (quantized_c0_unsigned - OFFSET) / POLY_SCALE
    c1_r = (quantized_c1_unsigned - OFFSET) / POLY_SCALE
    c2_r = (quantized_c2_unsigned - OFFSET) / POLY_SCALE
    return c0_r + c1_r * z + c2_r * z ** 2

sim_probs = poly2_quantized_reconstructed(z_sim_all)
sim_preds = (sim_probs >= 0.5).astype(int)
sim_accuracy = accuracy_score(y_test, sim_preds)

print(f"True sigmoid accuracy:                {small_accuracy:.4f}")
print(f"Float polynomial-activation accuracy: {poly_accuracy:.4f}")
print(f"Quantized/offset CoFHE-sim accuracy:  {sim_accuracy:.4f}")

True sigmoid accuracy:                0.7450
Float polynomial-activation accuracy: 0.7450
Quantized/offset CoFHE-sim accuracy:  0.7100

In [35]:
def quantize_signed_bias(value, scale=SCALE * FEATURE_SCALE):
    return int(round(value * scale))

quantized_bias_signed = quantize_signed_bias(bias)
quantized_bias_unsigned = to_unsigned(quantized_bias_signed)

print("Bias before rounding:", bias)
print("Quantized unsigned bias (corrected scale):", quantized_bias_unsigned)

Bias before rounding: 0.769379649489387
Quantized unsigned bias (corrected scale): 176938

In [36]:
z_sim_all = np.array([full_simulation(row) for row in X_test_small])

sim_probs = poly2_quantized_reconstructed(z_sim_all)
sim_preds = (sim_probs >= 0.5).astype(int)
sim_accuracy = accuracy_score(y_test, sim_preds)

print(f"True sigmoid accuracy:                {small_accuracy:.4f}")
print(f"Float polynomial-activation accuracy: {poly_accuracy:.4f}")
print(f"Quantized/offset CoFHE-sim accuracy:  {sim_accuracy:.4f}")

# also check z reconstruction directly against float z, sample by sample
z_error = np.abs(z_sim_all - z_test)
print(f"Mean absolute z error: {z_error.mean():.6f}  (should now be small, was previously large due to bias bug)")

True sigmoid accuracy:                0.7450
Float polynomial-activation accuracy: 0.7450
Quantized/offset CoFHE-sim accuracy:  0.7450
Mean absolute z error: 0.004708  (should now be small, was previously large due to bias bug)

In [37]:
EUINT32_MAX = 2**32 - 1

max_weight_term = max(quantized_weights_unsigned) * (FEATURE_SCALE * max(np.abs(X_test_small).max(), 1))
max_bias_term = quantized_bias_unsigned

print(f"Largest weight×feature term: {max_weight_term:,.0f}")
print(f"Bias term:                   {max_bias_term:,.0f}")
print(f"euint32 max:                 {EUINT32_MAX:,}")
print(f"Weight term headroom OK: {max_weight_term < EUINT32_MAX}")
print(f"Bias term headroom OK:   {max_bias_term < EUINT32_MAX}")

# also check the SUM doesn't overflow, not just individual terms --
# this is what actually gets added on-chain before offset removal
worst_case_sum = sum(qw * (FEATURE_SCALE * max(np.abs(X_test_small).max(), 1))
                      for qw in quantized_weights_unsigned) + quantized_bias_unsigned
print(f"Worst-case full sum: {worst_case_sum:,.0f}")
print(f"Sum headroom OK: {worst_case_sum < EUINT32_MAX}")

Largest weight×feature term: 608,076,000
Bias term:                   176,938
euint32 max:                 4,294,967,295
Weight term headroom OK: True
Bias term headroom OK:   True
Worst-case full sum: 3,615,806,938
Sum headroom OK: True

In [38]:
EUINT32_MAX = 2**32 - 1

# per-feature actual max (not one shared max across all columns)
per_feature_max = np.abs(X_test_small).max(axis=0)
print("Per-feature max values:", dict(zip(top_features, per_feature_max)))

real_worst_case_sum = sum(
    qw * int(round(fmax * FEATURE_SCALE))
    for qw, fmax in zip(quantized_weights_unsigned, per_feature_max)
) + quantized_bias_unsigned

print(f"Realistic worst-case sum: {real_worst_case_sum:,.0f}")
print(f"euint32 max:              {EUINT32_MAX:,}")
print(f"Headroom remaining:       {EUINT32_MAX - real_worst_case_sum:,.0f} "
      f"({100*(EUINT32_MAX - real_worst_case_sum)/EUINT32_MAX:.1f}%)")

# also stress-test against a Duration beyond what you happened to see in the test set --
# German Credit's real range goes up to 72 months; confirm your test set actually covers that
print("Duration (Attribute2) test-set range:", X_test_small[:, 0].min(), "to", X_test_small[:, 0].max())

Per-feature max values: {'remainder__Attribute2': np.float64(60.0), 'cat__Attribute1_A11': np.float64(1.0), 'cat__Attribute1_A13': np.float64(1.0), 'cat__Attribute1_A14': np.float64(1.0), 'cat__Attribute3_A32': np.float64(1.0), 'cat__Attribute3_A34': np.float64(1.0)}
Realistic worst-case sum: 650,248,638
euint32 max:              4,294,967,295
Headroom remaining:       3,644,718,657 (84.9%)
Duration (Attribute2) test-set range: 5.0 to 60.0

In [39]:
# force the true documented max for Duration regardless of what's in this test split
per_feature_max_safe = per_feature_max.copy()
per_feature_max_safe[0] = 72  # Attribute2 documented max

real_worst_case_sum_safe = sum(
    qw * int(round(fmax * FEATURE_SCALE))
    for qw, fmax in zip(quantized_weights_unsigned, per_feature_max_safe)
) + quantized_bias_unsigned

print(f"Worst-case sum (documented max Duration=72): {real_worst_case_sum_safe:,.0f}")
print(f"Headroom OK: {real_worst_case_sum_safe < EUINT32_MAX}")

Worst-case sum (documented max Duration=72): 770,210,238
Headroom OK: True

In [40]:
print("=" * 60)
print("FINAL CONTRACT-READY CONSTANTS")
print("=" * 60)
print(f"Features (order matters, matches Profile struct): {top_features}")
print(f"SCALE = {SCALE}")
print(f"FEATURE_SCALE = {FEATURE_SCALE}")
print(f"OFFSET = {OFFSET}")
print(f"Quantized unsigned weights: {quantized_weights_unsigned}")
print(f"Quantized unsigned bias (corrected): {quantized_bias_unsigned}")
print(f"Quantized unsigned poly coeffs [c0, c1, c2]: "
      f"[{quantized_c0_unsigned}, {quantized_c1_unsigned}, {quantized_c2_unsigned}]")
print(f"POLY_SCALE = {POLY_SCALE}")
print("=" * 60)
print(f"Accuracy: true sigmoid {small_accuracy:.4f} | float poly {poly_accuracy:.4f} | "
      f"quantized CoFHE-sim {sim_accuracy:.4f}")
print(f"Overflow headroom (documented max Duration=72): "
      f"{100*(EUINT32_MAX - real_worst_case_sum_safe)/EUINT32_MAX:.1f}%")
print("=" * 60)

============================================================
FINAL CONTRACT-READY CONSTANTS
============================================================
Features (order matters, matches Profile struct): ['remainder__Attribute2', 'cat__Attribute1_A11', 'cat__Attribute1_A13', 'cat__Attribute1_A14', 'cat__Attribute3_A32', 'cat__Attribute3_A34']
SCALE = 1000
FEATURE_SCALE = 100
OFFSET = 100000
Quantized unsigned weights: [99968, 99479, 100414, 101346, 100388, 101010]
Quantized unsigned bias (corrected): 176938
Quantized unsigned poly coeffs [c0, c1, c2]: [622897, 300176, 83038]
POLY_SCALE = 1000000
============================================================
Accuracy: true sigmoid 0.7450 | float poly 0.7450 | quantized CoFHE-sim 0.7450
Overflow headroom (documented max Duration=72): 82.1%
============================================================